[package]
name = "polarcoaster"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polar-core = { path = "../polar-core", version = "=0.24.0" }
serde = "1.0"
serde_json = "1.0.61"
raylib = "3.7"
